@baseUrl = http://localhost:3000/api/classSessions

### 1. Obtener todas las sesiones de clases
GET {{baseUrl}}

### 2. Obtener una sesión por ID
GET {{baseUrl}}/1

### 3. Crear una sesión de clase válida
POST {{baseUrl}}
Content-Type: application/json

{
  "classScheduleId": 2,
  "date": "2026-10-15",
  "startTime": "10:00",
  "instructorId": 1,
  "status": "SCHEDULED"
}

### 4. Actualizar una sesión existente
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "startTime": "11:00",
  "instructorId": 1
}

### 5. Eliminar una sesión de clase
DELETE {{baseUrl}}/1

### 6. Obtener sesiones por instructor
GET {{baseUrl}}/instructor/1

### 7. Obtener sesiones por clase
GET {{baseUrl}}/schedule/2
